GET http://localhost:3000
###
POST http://localhost:3000/api/user/register
content-type: application/json

{
    "name": "Sushant Bfdsf",
    "email" : "ke8@gail.com",
    "password" : "s15dD@/.ssS"
}
###
GET http://localhost:3000/api/user/alluser
