GET http://localhost:3000
###
GET http://localhost:3000/api/upload/allupload

###
POST http://localhost:3000/api/user/register
content-type: application/json

{
    "name": "Sushant Bfdsfs",
    "email" : "ke811e@gail.com",
    "password" : "s15dD@/.ssS"
}
###
PATCH  http://localhost:3000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzksImRhdGUiOiIyMDIxLTA2LTI4VDE3OjU2OjMwLjQ5M1oiLCJpYXQiOjE2MjQ5MDI5OTB9._5OH42c2Pu_vz5ctlRBhFWvWjBI7G_DQS-GRdkppKjw

content-type: application/json
{
    "name": "SushanT",
    "email" : "ke811e@gail.com",
    "password" : "s15dD@/.ssS"
}
###
GET http://localhost:3000/api/user/login
content-type: application/json

{
    "email" : "ke811e@gail.com",
    "password" : "s15dD@/.ssS"
}
###
GET  http://localhost:3000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzksImRhdGUiOiIyMDIxLTA2LTI4VDE3OjQ4OjU5Ljc2NloiLCJpYXQiOjE2MjQ5MDI1Mzl9.tglvaFWfzH4qq3ITlDxV9AJQJV_7hnq9lK_pUhfO7PY