GET http://localhost:3000
###
POST http://localhost:3000/api/user/register
content-type: application/json

{
    "name": "sushant",
    "email" : "basak@gmail.com",
    "password" : "s15dD@/.ssS"
}
###
GET http://localhost:3000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjAsImRhdGUiOjE2MjYyNDc4MTYzNTQsImlhdCI6MTYyNjI0NzgxNn0.C3LFmsj2p-u4eDEEX52dO5jgwHW-vbETJjNjW73V-hY
###
DELETE http://localhost:3000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDYsImRhdGUiOjE2MjQ5OTA1NTg3MTksImlhdCI6MTYyNDk5MDU1OH0.l2yDpAxLAAQkapgb-vj7iyNQEbpl6Wy5qN2aw-pH6fY
###
PATCH  http://localhost:3000/api/user/me
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsImRhdGUiOjE2MjQ5OTE0ODQ3NTksImlhdCI6MTYyNDk5MTQ4NH0.rc9_vrsepZC7B5KYkNK0lEmZ2xKAeizGELJrndNWiug

{
    "name": "SushanT Basak",
    "email" : "kevin@gmail.com",
    "password" : "s15dD@/.ssS"
}
###
GET http://localhost:3000/api/user/login
content-type: application/json

{
    "email" : "basak@gmail.com",
    "password" : "s15dD@/.ssS"
}
###
POST http://localhost:3000/api/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsImRhdGUiOjE2MjQ5OTM0NDYwNjEsImlhdCI6MTYyNDk5MzQ0Nn0.7ypgPknC0kzVbI1jipkk4k3gW5VV8CR4Xq2q6uCVVqY

###
POST http://localhost:3000/api/user/logoutall
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsImRhdGUiOjE2MjQ5OTM1MDI2MzEsImlhdCI6MTYyNDk5MzUwMn0.rGh3wTU9HQRjnxUmxBKds3VBGTkBSgDm6KwcKlGmvYA
